### ISSUE TITLE
Widgets wander based on filename

### ISSUE THREAD

**Issue by paulmcnamee** [iscoe/dragonfly#26]
The "top right" widgets (i.e., cascade, previous, next, save, settings) adjust position based on the length of the filename at the top left.  This makes action sequences like "next, next, next" problematic unless the user continually looks at the widget.  It is not enough to position the cursor over the widget once, and then assume that the same widget will still be there after a click.  It would be nice if their positions were fixed.

**Comment by cash** [comment]
Are you seeing this?
![image](https://user-images.githubusercontent.com/199558/51567908-64506a80-1e66-11e9-84f7-1f5e9f2ac2dc.png)

**Comment by cash** [comment]
I'm told this is not the issue (screen too small so that controls drop down). Instead, the shifting is due to the scrollbar. If the document is not long, there is no scroll bar. When you move to a longer document, the scrollbar appears and moves to the controls to the left. There are some display fixes for that (forcing the scrollbar to always be there) and I could also add keyboard shortcuts using the arrow keys.
